-- MySQL Script generated by MySQL Workbench
-- Wed May 12 12:43:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema licitacion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `licitacion` ;

-- -----------------------------------------------------
-- Schema licitacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `licitacion` DEFAULT CHARACTER SET utf8 ;
USE `licitacion` ;

-- -----------------------------------------------------
-- Table `licitacion`.`tbl_address_format_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_address_format_code` (
  `address_format_code` INT(11) NOT NULL,
  `description` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`address_format_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_contract_folder_status_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_contract_folder_status_code` (
  `contract_folder_status_code` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`contract_folder_status_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_contracting_party_type_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_contracting_party_type_code` (
  `contracting_party_type_code` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`contracting_party_type_code`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_country_identification_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_country_identification_code` (
  `code` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_country_subentity_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_country_subentity_code` (
  `code` VARCHAR(5) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_cpv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_cpv` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_dgpe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_dgpe` (
  `dgpe` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_tabla` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`dgpe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_type_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_type_code` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_subtype_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_subtype_code` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  `type_code` INT(11) NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_tbl_subtype_code_tbl_type_code1_idx` (`type_code` ASC),
  CONSTRAINT `fk_tbl_subtype_code_tbl_type_code1`
    FOREIGN KEY (`type_code`)
    REFERENCES `licitacion`.`tbl_type_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_expedientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_expedientes` (
  `expedientes` INT(11) NOT NULL,
  `title` VARCHAR(2000) NOT NULL,
  `link` VARCHAR(2500) NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `objeto_contrato` VARCHAR(2000) NOT NULL,
  `valor_estimado` DECIMAL(12,2) NULL DEFAULT NULL,
  `presupuesto_sin_impuestos` DECIMAL(12,2) NULL DEFAULT NULL,
  `presupuesto_con_impuestos` DECIMAL(12,2) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `duracion` DECIMAL(17,0) NULL DEFAULT NULL,
  `unitcode` VARCHAR(45) NULL DEFAULT NULL,
  `typecode` INT(11) NULL DEFAULT NULL,
  `subtypecode` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`expedientes`),
  INDEX `typecode_idx` (`typecode` ASC),
  INDEX `subtypecode_idx` (`subtypecode` ASC),
  CONSTRAINT `subtypecode`
    FOREIGN KEY (`subtypecode`)
    REFERENCES `licitacion`.`tbl_subtype_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `typecode`
    FOREIGN KEY (`typecode`)
    REFERENCES `licitacion`.`tbl_type_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_expediente_cpv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_expediente_cpv` (
  `code` INT(11) NOT NULL,
  `expedientes` INT(11) NOT NULL,
  INDEX `fk_tbl_expediente_cpv_tbl_cpv1_idx` (`code` ASC),
  INDEX `fk_tbl_expediente_cpv_tbl_expedientes1_idx` (`expedientes` ASC),
  CONSTRAINT `fk_tbl_expediente_cpv_tbl_cpv1`
    FOREIGN KEY (`code`)
    REFERENCES `licitacion`.`tbl_cpv` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_expediente_cpv_tbl_expedientes1`
    FOREIGN KEY (`expedientes`)
    REFERENCES `licitacion`.`tbl_expedientes` (`expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_identification_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_identification_code` (
  `identification_code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `numericcode` INT(11) NOT NULL,
  PRIMARY KEY (`identification_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_modosid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_modosid` (
  `modosid` INT(11) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`modosid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_ids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_ids` (
  `ids` INT(11) NOT NULL AUTO_INCREMENT,
  `modosid` INT(11) NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ids`),
  INDEX `modosid_idx` (`modosid` ASC),
  CONSTRAINT `modosid`
    FOREIGN KEY (`modosid`)
    REFERENCES `licitacion`.`tbl_modosid` (`modosid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_ids_expedientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_ids_expedientes` (
  `ids_expedientes` INT(11) NOT NULL AUTO_INCREMENT,
  `ids` INT(11) NOT NULL,
  `expediente` INT(11) NOT NULL,
  `summary` VARCHAR(400) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ids_expedientes`),
  INDEX `ids_idx` (`ids` ASC),
  INDEX `expediente_idx` (`expediente` ASC),
  INDEX `estado_idx` (`estado` ASC),
  CONSTRAINT `estado`
    FOREIGN KEY (`estado`)
    REFERENCES `licitacion`.`tbl_contract_folder_status_code` (`contract_folder_status_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `expediente`
    FOREIGN KEY (`expediente`)
    REFERENCES `licitacion`.`tbl_expedientes` (`expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ids`
    FOREIGN KEY (`ids`)
    REFERENCES `licitacion`.`tbl_ids` (`ids`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_lugar_de_ejecucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_lugar_de_ejecucion` (
  `lugar_de_ejecucion` INT(11) NOT NULL AUTO_INCREMENT,
  `expedientes` INT(11) NOT NULL,
  `country_identification_code` VARCHAR(3) NULL DEFAULT NULL,
  `country_subentity_code` VARCHAR(5) NOT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `calle` VARCHAR(220) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(32) NULL DEFAULT NULL,
  `poblacion` VARCHAR(90) NULL DEFAULT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`lugar_de_ejecucion`),
  INDEX `fk_calle_tbl_country_identification_code1_idx` (`country_identification_code` ASC),
  INDEX `fk_calle_tbl_country_subentity_code1_idx` (`country_subentity_code` ASC),
  INDEX `fk_calle_tbl_expedientes1_idx` (`expedientes` ASC),
  CONSTRAINT `fk_calle_tbl_country_identification_code1`
    FOREIGN KEY (`country_identification_code`)
    REFERENCES `licitacion`.`tbl_country_identification_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calle_tbl_country_subentity_code1`
    FOREIGN KEY (`country_subentity_code`)
    REFERENCES `licitacion`.`tbl_country_subentity_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calle_tbl_expedientes1`
    FOREIGN KEY (`expedientes`)
    REFERENCES `licitacion`.`tbl_expedientes` (`expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_tipo_pliego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_tipo_pliego` (
  `id` INT(11) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_pliegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_pliegos` (
  `pliegos` INT(11) NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(200) NULL DEFAULT NULL,
  `uri` VARCHAR(2500) NULL DEFAULT NULL,
  `document_hash` VARCHAR(2500) NULL DEFAULT NULL,
  `file_name` VARCHAR(2500) NULL DEFAULT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expedientes` INT(11) NOT NULL,
  `tipo_pliego` INT(11) NOT NULL,
  PRIMARY KEY (`pliegos`),
  INDEX `fk_tbl_pliegos_tbl_expedientes1_idx` (`expedientes` ASC),
  INDEX `fk_tbl_pliegos_tbl_tipo_pliego1_idx` (`tipo_pliego` ASC),
  CONSTRAINT `fk_tbl_pliegos_tbl_expedientes1`
    FOREIGN KEY (`expedientes`)
    REFERENCES `licitacion`.`tbl_expedientes` (`expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pliegos_tbl_tipo_pliego1`
    FOREIGN KEY (`tipo_pliego`)
    REFERENCES `licitacion`.`tbl_tipo_pliego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_procedure_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_procedure_code` (
  `code` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_contracting_system_type_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_contracting_system_type_code` (
  `code` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_urgency_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_urgency_code` (
  `code` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_submission_method_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_submission_method_code` (
  `code` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_language` (
  `code` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_procurement_legislation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_procurement_legislation` (
  `code` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_type_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_type_code` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_subtype_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_subtype_code` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  `type_code` INT(11) NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_tbl_subtype_code_tbl_type_code1_idx` (`type_code` ASC),
  CONSTRAINT `fk_tbl_subtype_code_tbl_type_code1`
    FOREIGN KEY (`type_code`)
    REFERENCES `licitacion`.`tbl_type_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_expedientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_expedientes` (
  `expedientes` INT(11) NOT NULL,
  `title` VARCHAR(2000) NOT NULL,
  `link` VARCHAR(2500) NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `objeto_contrato` VARCHAR(2000) NOT NULL,
  `valor_estimado` DECIMAL(12,2) NULL DEFAULT NULL,
  `presupuesto_sin_impuestos` DECIMAL(12,2) NULL DEFAULT NULL,
  `presupuesto_con_impuestos` DECIMAL(12,2) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `duracion` DECIMAL(17,0) NULL DEFAULT NULL,
  `unitcode` VARCHAR(45) NULL DEFAULT NULL,
  `typecode` INT(11) NULL DEFAULT NULL,
  `subtypecode` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`expedientes`),
  INDEX `typecode_idx` (`typecode` ASC),
  INDEX `subtypecode_idx` (`subtypecode` ASC),
  CONSTRAINT `subtypecode`
    FOREIGN KEY (`subtypecode`)
    REFERENCES `licitacion`.`tbl_subtype_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `typecode`
    FOREIGN KEY (`typecode`)
    REFERENCES `licitacion`.`tbl_type_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_proceso_de_licitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_proceso_de_licitacion` (
  `proceso_de_licitacion` INT NOT NULL AUTO_INCREMENT,
  `expedientes` INT NOT NULL,
  `tipo_procedimiento` INT NOT NULL,
  `sistema_contratacion` INT NULL,
  `tramitacion` INT NULL,
  `presentacion_oferta` INT NULL,
  `regulacion` VARCHAR(15) NULL,
  `subasta_electronica` TINYINT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`proceso_de_licitacion`),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_expedientes1_idx` (`expedientes` ASC),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_procedure_code1_idx` (`tipo_procedimiento` ASC),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_contracting_system_type_co_idx` (`sistema_contratacion` ASC),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_urgency_code1_idx` (`tramitacion` ASC),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_submission_method_code1_idx` (`presentacion_oferta` ASC),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_procurement_legislation1_idx` (`regulacion` ASC),
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_expedientes1`
    FOREIGN KEY (`expedientes`)
    REFERENCES `licitacion`.`tbl_expedientes` (`expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_procedure_code1`
    FOREIGN KEY (`tipo_procedimiento`)
    REFERENCES `licitacion`.`tbl_procedure_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_contracting_system_type_code1`
    FOREIGN KEY (`sistema_contratacion`)
    REFERENCES `licitacion`.`tbl_contracting_system_type_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_urgency_code1`
    FOREIGN KEY (`tramitacion`)
    REFERENCES `licitacion`.`tbl_urgency_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_submission_method_code1`
    FOREIGN KEY (`presentacion_oferta`)
    REFERENCES `licitacion`.`tbl_submission_method_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_procurement_legislation1`
    FOREIGN KEY (`regulacion`)
    REFERENCES `licitacion`.`tbl_procurement_legislation` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_proceso_licitacion_idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_proceso_licitacion_idiomas` (
  `proceso_de_licitacion` INT NOT NULL,
  `idioma` VARCHAR(10) NOT NULL,
  INDEX `fk_tbl_proceso_licitacion_idiomas_tbl_proceso_de_licitacion_idx` (`proceso_de_licitacion` ASC),
  INDEX `fk_tbl_proceso_licitacion_idiomas_tbl_language1_idx` (`idioma` ASC),
  CONSTRAINT `fk_tbl_proceso_licitacion_idiomas_tbl_proceso_de_licitacion1`
    FOREIGN KEY (`proceso_de_licitacion`)
    REFERENCES `licitacion`.`tbl_proceso_de_licitacion` (`proceso_de_licitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_licitacion_idiomas_tbl_language1`
    FOREIGN KEY (`idioma`)
    REFERENCES `licitacion`.`tbl_language` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `licitacion` ;

-- -----------------------------------------------------
-- Placeholder table for view `licitacion`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`view1` (`id` INT);

-- -----------------------------------------------------
-- procedure newCPV
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newCPV`(
	IN code INT, 
    IN nombre VARCHAR(300))
BEGIN 
	START TRANSACTION;
	INSERT INTO tbl_cpv (code, nombre)
    VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newCountryIdentificationCode
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newCountryIdentificationCode`(
	IN code VARCHAR(3),
	IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
	INSERT INTO tbl_country_identification_code (code, nombre)
	VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newCountrySubentityCode
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newCountrySubentityCode`(
IN code VARCHAR(5),
IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_country_subentity_code (code, nombre)
        VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newExpediente
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newExpediente`(
	IN expedientes INT, 
	IN title VARCHAR(2000),
    IN link VARCHAR(2500),
    IN objeto_contrato VARCHAR(2000),
    IN valor_estimado DECIMAL(12,2),
    IN presupuesto_sin_impuestos DECIMAL(12,2),
    IN presupuesto_con_impuestos DECIMAL(12,2),
    IN start_date DATE, 
    IN end_date DATE,
    IN duracion DECIMAL(17,0),
    IN unitcode VARCHAR(45),
    IN typecode INT, 
    IN subtypecode INT)
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_expedientes (expedientes, title, link, objeto_contrato, valor_estimado, presupuesto_sin_impuestos,
				presupuesto_con_impuestos, start_date, end_date, duracion, unitcode, typecode, subtypecode)
		VALUES (expedientes, title, link, objeto_contrato, valor_estimado, presupuesto_sin_impuestos,
				presupuesto_con_impuestos, start_date, end_date, duracion, unitcode, typecode, subtypecode);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newExpediente_CPV
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newExpediente_CPV`(
	IN code INT,
    IN expedientes INT)
BEGIN
	START TRANSACTION;
    
    INSERT INTO tbl_expediente_cpv (code, expedientes)
    VALUES (code, expedientes);
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newExpediente_Ids
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newExpediente_Ids`(
	IN ids INT,
    IN expediente INT,
    IN summary VARCHAR(400),
    IN updated TIMESTAMP,
    IN estado VARCHAR(45))
BEGIN
	START TRANSACTION;
    
		INSERT INTO tbl_ids_expedientes (ids, expediente, summary, updated, estado)
        VALUES (ids, expediente, summary, updated, estado);
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newIds
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newIds`(
	IN modos_id INT,
    OUT ids INT)
BEGIN 
	START TRANSACTION;
	INSERT INTO tbl_ids (modosid)
    VALUES (modos_id);
    
    SET ids = last_insert_id();
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newLugarDeEjecucion
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newLugarDeEjecucion`(
	IN expedientes INT,
    IN country_identification_code VARCHAR(3),
    IN country_subentity_code VARCHAR(5),
    IN pais VARCHAR(100),
    IN calle VARCHAR(220),
    IN codigo_postal VARCHAR(32),
    IN poblacion VARCHAR(90))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_lugar_de_ejecucion (expedientes, country_identification_code, country_subentity_code, pais, calle, codigo_postal, poblacion)
        VALUES (expedientes, country_identification_code, country_subentity_code, pais, calle, codigo_postal, poblacion);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newPliego
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newPliego`(
	IN id VARCHAR(200),
    IN uri VARCHAR(2500),
    IN document_hash VARCHAR(2500),
    IN file_name VARCHAR(2500),
    IN expedientes INT,
    IN tipo_pliego INT)
BEGIN
	START TRANSACTION;
    
		INSERT INTO tbl_pliegos (id, uri, document_hash, file_name, expedientes, tipo_pliego)
        VALUES (id, uri, document_hash, file_name, expedientes, tipo_pliego);
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newSubtypeCode
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newSubtypeCode`(
	IN code INT, 
    IN nombre VARCHAR(300),
    IN type_code INT)
BEGIN 
	INSERT INTO tbl_subtype_code (code, nombre, type_code)
    VALUES (code, nombre, type_code);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure searchExpediente
-- -----------------------------------------------------

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `searchExpediente`(
	IN id INT, 
    OUT existe BOOLEAN)
BEGIN
	START TRANSACTION;
    SET existe = 
		CASE WHEN (SELECT COUNT(*) FROM tbl_expedientes WHERE expedientes = id) = 1 THEN 1
        ELSE 0
        END;
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `licitacion`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`view1`;
USE `licitacion`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `licitacion`.`tbl_type_code`
-- -----------------------------------------------------
START TRANSACTION;
USE `licitacion`;
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (1, 'Suministros');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (2, 'Servicios');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (3, 'Obras');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (21, 'Gestión de servicios');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (31, 'Concesión de obras públicas');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (40, 'Colaboración entre el sector público y el sector privado');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (7, 'Administrativo especial');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (8, 'Privado');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (50, 'Patrimonial');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (999, 'Otros');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (0, 'null');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (32, 'Concesión de obras');
INSERT INTO `licitacion`.`tbl_type_code` (`code`, `nombre`) VALUES (22, 'Concesión de servicios');

COMMIT;


-- -----------------------------------------------------
-- Data for table `licitacion`.`tbl_subtype_code`
-- -----------------------------------------------------
START TRANSACTION;
USE `licitacion`;
INSERT INTO `licitacion`.`tbl_subtype_code` (`code`, `nombre`, `type_code`) VALUES (0, 'null', 0);

COMMIT;

