-- MySQL Script generated by MySQL Workbench
-- Mon May  3 11:31:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema licitacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema licitacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `licitacion` DEFAULT CHARACTER SET latin1 ;
USE `licitacion` ;

-- -----------------------------------------------------
-- Table `licitacion`.`tbl_address_format_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_address_format_code` (
  `address_format_code` INT NOT NULL,
  `description` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`address_format_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_postal_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_postal_address` (
  `postal_address` INT NOT NULL AUTO_INCREMENT,
  `addressformatcode` INT NULL,
  `cityname` VARCHAR(90) NOT NULL,
  `postalzone` VARCHAR(32) NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`postal_address`),
  INDEX `fk_tbl_postal_address_tbl_address_format_code` (`addressformatcode` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_postal_address_tbl_address_format_code`
    FOREIGN KEY (`addressformatcode`)
    REFERENCES `licitacion`.`tbl_address_format_code` (`address_format_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_address_line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_address_line` (
  `address_line` INT NOT NULL AUTO_INCREMENT,
  `line` VARCHAR(220) NOT NULL,
  `postaladdress` INT NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`address_line`),
  INDEX `fk_tbl_address_line_tbl_postal_address1_idx` (`postaladdress` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_address_line_tbl_postal_address1`
    FOREIGN KEY (`postaladdress`)
    REFERENCES `licitacion`.`tbl_postal_address` (`postal_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_contact` (
  `contact` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NULL DEFAULT NULL,
  `electronicmail` VARCHAR(200) NULL DEFAULT NULL,
  `telephone` VARCHAR(50) NULL DEFAULT NULL,
  `telefax` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`contact`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_modosid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_modosid` (
  `modosid` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`modosid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_ids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_ids` (
  `ids` INT NOT NULL AUTO_INCREMENT,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modosid` INT NOT NULL,
  PRIMARY KEY (`ids`),
  INDEX `fk_tbl_ids_tbl_modosid` (`modosid` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_ids_tbl_modosid`
    FOREIGN KEY (`modosid`)
    REFERENCES `licitacion`.`tbl_modosid` (`modosid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_entrys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_entrys` (
  `entrys` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(2500) NOT NULL,
  `link` VARCHAR(2500) NOT NULL,
  `summary` VARCHAR(400) NOT NULL,
  `title` VARCHAR(2000) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ids` INT NOT NULL,
  PRIMARY KEY (`entrys`),
  INDEX `fk_tbl_entrys_tbl_ids` (`ids` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_entrys_tbl_ids`
    FOREIGN KEY (`ids`)
    REFERENCES `licitacion`.`tbl_ids` (`ids`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_contract_folder_status_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_contract_folder_status_code` (
  `contract_folder_status_code` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`contract_folder_status_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_contract_folder_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_contract_folder_status` (
  `contract_folder_status` INT NOT NULL AUTO_INCREMENT,
  `contractfolderid` VARCHAR(50) NOT NULL,
  `contractfolderstatuscode` VARCHAR(50) NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `entry` INT NOT NULL,
  PRIMARY KEY (`contract_folder_status`),
  INDEX `fk_tbl_contract_folder_status_tbl_entrys` (`entry` ASC) VISIBLE,
  INDEX `fk_tbl_contract_folder_status_tbl_contract_folder_status_co_idx` (`contractfolderstatuscode` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_contract_folder_status_tbl_entrys`
    FOREIGN KEY (`entry`)
    REFERENCES `licitacion`.`tbl_entrys` (`entrys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_contract_folder_status_tbl_contract_folder_status_code1`
    FOREIGN KEY (`contractfolderstatuscode`)
    REFERENCES `licitacion`.`tbl_contract_folder_status_code` (`contract_folder_status_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_contracting_party_type_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_contracting_party_type_code` (
  `contracting_party_type_code` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`contracting_party_type_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_identification_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_identification_code` (
  `identification_code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `numericcode` INT(11) NOT NULL,
  PRIMARY KEY (`identification_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_country` (
  `country` INT NOT NULL AUTO_INCREMENT,
  `identificationcode` VARCHAR(3) NOT NULL,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`country`),
  INDEX `fk_tbl_country_tbl_identification_code` (`identificationcode` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_country_tbl_identification_code`
    FOREIGN KEY (`identificationcode`)
    REFERENCES `licitacion`.`tbl_identification_code` (`identification_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_dgpe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_dgpe` (
  `dgpe` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_tabla` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`dgpe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_located_contracting_party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_located_contracting_party` (
  `located_contracting_party` INT NOT NULL AUTO_INCREMENT,
  `contractingpartytypecode` INT NOT NULL,
  `contractfolderstatus` INT NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`located_contracting_party`),
  INDEX `fk_tbl_located_contracting_party_tbl_contract_folder_status` (`contractfolderstatus` ASC) VISIBLE,
  INDEX `fk_tbl_located_contracting_party_tbl_contracting_party_type_code` (`contractingpartytypecode` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_located_contracting_party_tbl_contract_folder_status`
    FOREIGN KEY (`contractfolderstatus`)
    REFERENCES `licitacion`.`tbl_contract_folder_status` (`contract_folder_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_located_contracting_party_tbl_contracting_party_type_code`
    FOREIGN KEY (`contractingpartytypecode`)
    REFERENCES `licitacion`.`tbl_contracting_party_type_code` (`contracting_party_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_parent_located_party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_parent_located_party` (
  `parent_located_party` INT NOT NULL AUTO_INCREMENT,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `locatedcontractingparty` INT NOT NULL,
  PRIMARY KEY (`parent_located_party`),
  INDEX `fk_tbl_parent_located_party_tbl_located_contracting_party1_idx` (`locatedcontractingparty` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_parent_located_party_tbl_located_contracting_party1`
    FOREIGN KEY (`locatedcontractingparty`)
    REFERENCES `licitacion`.`tbl_located_contracting_party` (`located_contracting_party`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_party` (
  `party` INT NOT NULL AUTO_INCREMENT,
  `websiteuri` VARCHAR(256) NULL DEFAULT NULL,
  `buyerprofileuriid` VARCHAR(500) NULL DEFAULT NULL,
  `locatedcontractingparty` INT NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`party`),
  INDEX `fk_tbl_party_tbl_located_contracting_party1_idx` (`locatedcontractingparty` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_party_tbl_located_contracting_party1`
    FOREIGN KEY (`locatedcontractingparty`)
    REFERENCES `licitacion`.`tbl_located_contracting_party` (`located_contracting_party`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_party_identification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_party_identification` (
  `party_identification` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(250) NOT NULL,
  `schemename` VARCHAR(50) NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`party_identification`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_party_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_party_name` (
  `party_name` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`party_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_party_partyidentification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_party_partyidentification` (
  `party` INT NOT NULL,
  `partyidentification` INT NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_tbl_party_partyidentification_tbl_party` (`party` ASC) VISIBLE,
  INDEX `fk_tbl_party_partyidentification_tbl_partyidenfication` (`partyidentification` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_party_partyidentification_tbl_party`
    FOREIGN KEY (`party`)
    REFERENCES `licitacion`.`tbl_party` (`party`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_party_partyidentification_tbl_partyidenfication`
    FOREIGN KEY (`partyidentification`)
    REFERENCES `licitacion`.`tbl_party_identification` (`party_identification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_parentlocatedparty_partyname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_parentlocatedparty_partyname` (
  `partyname` INT NOT NULL,
  `parentlocatedparty` INT NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_tbl_party_name_has_tbl_parent_located_party_tbl_parent_l_idx` (`parentlocatedparty` ASC) VISIBLE,
  INDEX `fk_tbl_party_name_has_tbl_parent_located_party_tbl_party_na_idx` (`partyname` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_party_name_has_tbl_parent_located_party_tbl_party_name1`
    FOREIGN KEY (`partyname`)
    REFERENCES `licitacion`.`tbl_party_name` (`party_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_party_name_has_tbl_parent_located_party_tbl_parent_loc1`
    FOREIGN KEY (`parentlocatedparty`)
    REFERENCES `licitacion`.`tbl_parent_located_party` (`parent_located_party`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_party_partyname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_party_partyname` (
  `partyname` INT NOT NULL,
  `party` INT NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_tbl_party_name_has_tbl_party_tbl_party1_idx` (`party` ASC) VISIBLE,
  INDEX `fk_tbl_party_name_has_tbl_party_tbl_party_name1_idx` (`partyname` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_party_name_has_tbl_party_tbl_party_name1`
    FOREIGN KEY (`partyname`)
    REFERENCES `licitacion`.`tbl_party_name` (`party_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_party_name_has_tbl_party_tbl_party1`
    FOREIGN KEY (`party`)
    REFERENCES `licitacion`.`tbl_party` (`party`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_party_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_party_contact` (
  `contact` INT NOT NULL,
  `party` INT NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_tbl_contact_has_tbl_party_tbl_party1_idx` (`party` ASC) VISIBLE,
  INDEX `fk_tbl_contact_has_tbl_party_tbl_contact1_idx` (`contact` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_contact_has_tbl_party_tbl_contact1`
    FOREIGN KEY (`contact`)
    REFERENCES `licitacion`.`tbl_contact` (`contact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_contact_has_tbl_party_tbl_party1`
    FOREIGN KEY (`party`)
    REFERENCES `licitacion`.`tbl_party` (`party`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_party_postaladdress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_party_postaladdress` (
  `postaladdress` INT NOT NULL,
  `party` INT NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_tbl_postal_address_has_tbl_party_tbl_party1_idx` (`party` ASC) VISIBLE,
  INDEX `fk_tbl_postal_address_has_tbl_party_tbl_postal_address1_idx` (`postaladdress` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_postal_address_has_tbl_party_tbl_postal_address1`
    FOREIGN KEY (`postaladdress`)
    REFERENCES `licitacion`.`tbl_postal_address` (`postal_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_postal_address_has_tbl_party_tbl_party1`
    FOREIGN KEY (`party`)
    REFERENCES `licitacion`.`tbl_party` (`party`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_postaladdress_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_postaladdress_country` (
  `country` INT NOT NULL,
  `postaladdress` INT NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_tbl_country_has_tbl_postal_address_tbl_postal_address1_idx` (`postaladdress` ASC) VISIBLE,
  INDEX `fk_tbl_country_has_tbl_postal_address_tbl_country1_idx` (`country` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_country_has_tbl_postal_address_tbl_country1`
    FOREIGN KEY (`country`)
    REFERENCES `licitacion`.`tbl_country` (`country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_country_has_tbl_postal_address_tbl_postal_address1`
    FOREIGN KEY (`postaladdress`)
    REFERENCES `licitacion`.`tbl_postal_address` (`postal_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
