-- MySQL Script generated by MySQL Workbench
-- Fri May 14 12:49:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema licitacion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `licitacion` ;

-- -----------------------------------------------------
-- Schema licitacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `licitacion` DEFAULT CHARACTER SET utf8 ;
USE `licitacion` ;

-- -----------------------------------------------------
-- Table `licitacion`.`tbl_address_format_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_address_format_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_address_format_code` (
  `address_format_code` INT(11) NOT NULL,
  `description` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`address_format_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_contract_folder_status_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_contract_folder_status_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_contract_folder_status_code` (
  `code` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_contracting_party_type_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_contracting_party_type_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_contracting_party_type_code` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_contracting_system_type_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_contracting_system_type_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_contracting_system_type_code` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_country_identification_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_country_identification_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_country_identification_code` (
  `code` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_country_subentity_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_country_subentity_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_country_subentity_code` (
  `code` VARCHAR(5) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_cpv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_cpv` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_cpv` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_dgpe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_dgpe` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_dgpe` (
  `dgpe` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_tabla` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`dgpe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_type_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_type_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_type_code` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_subtype_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_subtype_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_subtype_code` (
  `code` INT(11) NOT NULL,
  `type_code` INT(11) NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`code`, `type_code`),
  INDEX `fk_tbl_subtype_code_tbl_type_code1_idx` (`type_code` ASC),
  CONSTRAINT `fk_tbl_subtype_code_tbl_type_code1`
    FOREIGN KEY (`type_code`)
    REFERENCES `licitacion`.`tbl_type_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_expedientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_expedientes` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_expedientes` (
  `expedientes` INT(11) NOT NULL,
  `title` VARCHAR(2000) NOT NULL,
  `link` VARCHAR(2500) NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `objeto_contrato` VARCHAR(2000) NOT NULL,
  `valor_estimado` DECIMAL(12,2) NULL DEFAULT NULL,
  `presupuesto_sin_impuestos` DECIMAL(12,2) NULL DEFAULT NULL,
  `presupuesto_con_impuestos` DECIMAL(12,2) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `duracion` DECIMAL(17,0) NULL DEFAULT NULL,
  `unitcode` VARCHAR(45) NULL DEFAULT NULL,
  `typecode` INT(11) NULL DEFAULT NULL,
  `subtypecode` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`expedientes`),
  INDEX `typecode_idx` (`typecode` ASC),
  INDEX `subtypecode_idx` (`subtypecode` ASC),
  CONSTRAINT `subtypecode`
    FOREIGN KEY (`subtypecode`)
    REFERENCES `licitacion`.`tbl_subtype_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `typecode`
    FOREIGN KEY (`typecode`)
    REFERENCES `licitacion`.`tbl_type_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_modosid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_modosid` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_modosid` (
  `modosid` INT(11) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`modosid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_ids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_ids` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_ids` (
  `ids` INT(11) NOT NULL AUTO_INCREMENT,
  `modosid` INT(11) NOT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ids`),
  INDEX `modosid_idx` (`modosid` ASC),
  CONSTRAINT `modosid`
    FOREIGN KEY (`modosid`)
    REFERENCES `licitacion`.`tbl_modosid` (`modosid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_ids_expedientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_ids_expedientes` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_ids_expedientes` (
  `ids_expedientes` INT(11) NOT NULL AUTO_INCREMENT,
  `ids` INT(11) NOT NULL,
  `expediente` INT(11) NOT NULL,
  `summary` VARCHAR(400) NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ids_expedientes`),
  INDEX `ids_idx` (`ids` ASC),
  INDEX `expediente_idx` (`expediente` ASC),
  INDEX `estado_idx` (`estado` ASC),
  CONSTRAINT `estado`
    FOREIGN KEY (`estado`)
    REFERENCES `licitacion`.`tbl_contract_folder_status_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `expediente`
    FOREIGN KEY (`expediente`)
    REFERENCES `licitacion`.`tbl_expedientes` (`expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ids`
    FOREIGN KEY (`ids`)
    REFERENCES `licitacion`.`tbl_ids` (`ids`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_entidad_adjudicadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_entidad_adjudicadora` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_entidad_adjudicadora` (
  `entidad_adjudicadora` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ubicacion_organica` VARCHAR(300) NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  `tipo_administracion` INT(11) NOT NULL,
  `sitio_web` VARCHAR(256) NULL DEFAULT NULL,
  `calle` VARCHAR(220) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(32) NULL DEFAULT NULL,
  `poblacion` VARCHAR(90) NULL DEFAULT NULL,
  `pais` VARCHAR(3) NULL DEFAULT NULL,
  `nombre_contacto` VARCHAR(300) NULL DEFAULT NULL,
  `telefono` VARCHAR(55) NULL DEFAULT NULL,
  `fax` VARCHAR(55) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(500) NULL DEFAULT NULL,
  `NIF` VARCHAR(200) NOT NULL,
  `ids` INT(11) NOT NULL,
  PRIMARY KEY (`entidad_adjudicadora`),
  INDEX `fk_tbl_entidad_adjudicadora_tbl_contracting_party_type_code_idx` (`tipo_administracion` ASC),
  INDEX `fk_tbl_entidad_adjudicadora_tbl_country_identification_code_idx` (`pais` ASC),
  INDEX `fk_tbl_entidad_adjudicadora_tbl_ids_expedientes1_idx` (`ids` ASC),
  CONSTRAINT `fk_tbl_entidad_adjudicadora_tbl_contracting_party_type_code1`
    FOREIGN KEY (`tipo_administracion`)
    REFERENCES `licitacion`.`tbl_contracting_party_type_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_entidad_adjudicadora_tbl_country_identification_code1`
    FOREIGN KEY (`pais`)
    REFERENCES `licitacion`.`tbl_country_identification_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_entidad_adjudicadora_tbl_ids_expedientes1`
    FOREIGN KEY (`ids`)
    REFERENCES `licitacion`.`tbl_ids_expedientes` (`ids_expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_id`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_id` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_id` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_id` VARCHAR(20) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_entidad_adjudicadora_id`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_entidad_adjudicadora_id` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_entidad_adjudicadora_id` (
  `entidad_adjudicadora` INT(11) NOT NULL,
  `id` INT(11) NOT NULL,
  INDEX `fk_tbl_entidad_adjudicadora_id_tbl_id1_idx` (`id` ASC),
  INDEX `fk_tbl_entidad_adjudicadora_id_tbl_entidad_adjudicadora1_idx` (`entidad_adjudicadora` ASC),
  CONSTRAINT `fk_tbl_entidad_adjudicadora_id_tbl_entidad_adjudicadora1`
    FOREIGN KEY (`entidad_adjudicadora`)
    REFERENCES `licitacion`.`tbl_entidad_adjudicadora` (`entidad_adjudicadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_entidad_adjudicadora_id_tbl_id1`
    FOREIGN KEY (`id`)
    REFERENCES `licitacion`.`tbl_id` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_expediente_cpv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_expediente_cpv` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_expediente_cpv` (
  `code` INT(11) NOT NULL,
  `expedientes` INT(11) NOT NULL,
  INDEX `fk_tbl_expediente_cpv_tbl_cpv1_idx` (`code` ASC),
  INDEX `fk_tbl_expediente_cpv_tbl_expedientes1_idx` (`expedientes` ASC),
  CONSTRAINT `fk_tbl_expediente_cpv_tbl_cpv1`
    FOREIGN KEY (`code`)
    REFERENCES `licitacion`.`tbl_cpv` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_expediente_cpv_tbl_expedientes1`
    FOREIGN KEY (`expedientes`)
    REFERENCES `licitacion`.`tbl_expedientes` (`expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_identification_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_identification_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_identification_code` (
  `identification_code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `numericcode` INT(11) NOT NULL,
  PRIMARY KEY (`identification_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_language` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_language` (
  `code` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_lugar_de_ejecucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_lugar_de_ejecucion` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_lugar_de_ejecucion` (
  `lugar_de_ejecucion` INT(11) NOT NULL AUTO_INCREMENT,
  `subentidad_nacional` VARCHAR(3) NULL DEFAULT NULL,
  `subentidad_territorial` VARCHAR(5) NOT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `calle` VARCHAR(220) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(32) NULL DEFAULT NULL,
  `poblacion` VARCHAR(90) NULL DEFAULT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ids` INT(11) NOT NULL,
  PRIMARY KEY (`lugar_de_ejecucion`),
  INDEX `fk_calle_tbl_country_identification_code1_idx` (`subentidad_nacional` ASC),
  INDEX `fk_calle_tbl_country_subentity_code1_idx` (`subentidad_territorial` ASC),
  INDEX `fk_tbl_lugar_de_ejecucion_tbl_ids_expedientes1_idx` (`ids` ASC),
  CONSTRAINT `fk_calle_tbl_country_identification_code1`
    FOREIGN KEY (`subentidad_nacional`)
    REFERENCES `licitacion`.`tbl_country_identification_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calle_tbl_country_subentity_code1`
    FOREIGN KEY (`subentidad_territorial`)
    REFERENCES `licitacion`.`tbl_country_subentity_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_lugar_de_ejecucion_tbl_ids_expedientes1`
    FOREIGN KEY (`ids`)
    REFERENCES `licitacion`.`tbl_ids_expedientes` (`ids_expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_tipo_plazo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_tipo_plazo` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_tipo_plazo` (
  `tipo_plazo` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_plazo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_plazo_de_obtencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_plazo_de_obtencion` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_plazo_de_obtencion` (
  `id_plazo_de_obtencion` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_plazo` INT(11) NOT NULL,
  `ids` INT(11) NOT NULL,
  PRIMARY KEY (`id_plazo_de_obtencion`),
  INDEX `fk_tbl_plazo_de_obtencion_table11_idx` (`tipo_plazo` ASC),
  INDEX `fk_tbl_plazo_de_obtencion_tbl_ids_expedientes1_idx` (`ids` ASC),
  CONSTRAINT `fk_tbl_plazo_de_obtencion_table11`
    FOREIGN KEY (`tipo_plazo`)
    REFERENCES `licitacion`.`tbl_tipo_plazo` (`tipo_plazo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_plazo_de_obtencion_tbl_ids_expedientes1`
    FOREIGN KEY (`ids`)
    REFERENCES `licitacion`.`tbl_ids_expedientes` (`ids_expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_tipo_pliego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_tipo_pliego` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_tipo_pliego` (
  `id` INT(11) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_pliegos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_pliegos` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_pliegos` (
  `pliegos` INT(11) NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(200) NULL DEFAULT NULL,
  `uri` VARCHAR(2500) NULL DEFAULT NULL,
  `document_hash` VARCHAR(2500) NULL DEFAULT NULL,
  `file_name` VARCHAR(2500) NULL DEFAULT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_pliego` INT(11) NOT NULL,
  `expedientes` INT(11) NOT NULL,
  PRIMARY KEY (`pliegos`),
  INDEX `fk_tbl_pliegos_tbl_tipo_pliego1_idx` (`tipo_pliego` ASC),
  INDEX `fk_tbl_pliegos_tbl_expedientes1_idx` (`expedientes` ASC),
  CONSTRAINT `fk_tbl_pliegos_tbl_tipo_pliego1`
    FOREIGN KEY (`tipo_pliego`)
    REFERENCES `licitacion`.`tbl_tipo_pliego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pliegos_tbl_expedientes1`
    FOREIGN KEY (`expedientes`)
    REFERENCES `licitacion`.`tbl_expedientes` (`expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_procedure_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_procedure_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_procedure_code` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_procurement_legislation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_procurement_legislation` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_procurement_legislation` (
  `code` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_submission_method_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_submission_method_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_submission_method_code` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_urgency_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_urgency_code` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_urgency_code` (
  `code` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_proceso_de_licitacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_proceso_de_licitacion` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_proceso_de_licitacion` (
  `proceso_de_licitacion` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_procedimiento` INT(11) NOT NULL,
  `sistema_contratacion` INT(11) NULL DEFAULT NULL,
  `tramitacion` INT(11) NULL DEFAULT NULL,
  `presentacion_oferta` INT(11) NULL DEFAULT NULL,
  `regulacion` VARCHAR(15) NULL DEFAULT NULL,
  `subasta_electronica` TINYINT(4) NULL DEFAULT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ids` INT(11) NOT NULL,
  PRIMARY KEY (`proceso_de_licitacion`),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_procedure_code1_idx` (`tipo_procedimiento` ASC),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_contracting_system_type_co_idx` (`sistema_contratacion` ASC),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_urgency_code1_idx` (`tramitacion` ASC),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_submission_method_code1_idx` (`presentacion_oferta` ASC),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_procurement_legislation1_idx` (`regulacion` ASC),
  INDEX `fk_tbl_proceso_de_licitacion_tbl_ids_expedientes1_idx` (`ids` ASC),
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_contracting_system_type_code1`
    FOREIGN KEY (`sistema_contratacion`)
    REFERENCES `licitacion`.`tbl_contracting_system_type_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_procedure_code1`
    FOREIGN KEY (`tipo_procedimiento`)
    REFERENCES `licitacion`.`tbl_procedure_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_procurement_legislation1`
    FOREIGN KEY (`regulacion`)
    REFERENCES `licitacion`.`tbl_procurement_legislation` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_submission_method_code1`
    FOREIGN KEY (`presentacion_oferta`)
    REFERENCES `licitacion`.`tbl_submission_method_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_urgency_code1`
    FOREIGN KEY (`tramitacion`)
    REFERENCES `licitacion`.`tbl_urgency_code` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_de_licitacion_tbl_ids_expedientes1`
    FOREIGN KEY (`ids`)
    REFERENCES `licitacion`.`tbl_ids_expedientes` (`ids_expedientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `licitacion`.`tbl_proceso_licitacion_idiomas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licitacion`.`tbl_proceso_licitacion_idiomas` ;

CREATE TABLE IF NOT EXISTS `licitacion`.`tbl_proceso_licitacion_idiomas` (
  `proceso_de_licitacion` INT(11) NOT NULL,
  `idioma` VARCHAR(10) NOT NULL,
  INDEX `fk_tbl_proceso_licitacion_idiomas_tbl_proceso_de_licitacion_idx` (`proceso_de_licitacion` ASC),
  INDEX `fk_tbl_proceso_licitacion_idiomas_tbl_language1_idx` (`idioma` ASC),
  CONSTRAINT `fk_tbl_proceso_licitacion_idiomas_tbl_language1`
    FOREIGN KEY (`idioma`)
    REFERENCES `licitacion`.`tbl_language` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proceso_licitacion_idiomas_tbl_proceso_de_licitacion1`
    FOREIGN KEY (`proceso_de_licitacion`)
    REFERENCES `licitacion`.`tbl_proceso_de_licitacion` (`proceso_de_licitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `licitacion` ;

-- -----------------------------------------------------
-- procedure newCPV
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newCPV`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newCPV`(
	IN code INT, 
    IN nombre VARCHAR(300))
BEGIN 
	START TRANSACTION;
	INSERT INTO tbl_cpv (code, nombre)
    VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newContractFolderStatusCode
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newContractFolderStatusCode`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newContractFolderStatusCode`(
	IN code VARCHAR(50),
    IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_contract_folder_status_code (code, nombre)
        VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newContractingPartyTypeCode
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newContractingPartyTypeCode`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newContractingPartyTypeCode`(
	IN code INT,
    IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_contracting_party_type_code (code, nombre)
        VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newContractingSystemTypeCode
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newContractingSystemTypeCode`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newContractingSystemTypeCode`(
	IN code INT,
    IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_contracting_system_type_code (code, nombre)
        VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newCountryIdentificationCode
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newCountryIdentificationCode`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newCountryIdentificationCode`(
	IN code VARCHAR(3),
	IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
	INSERT INTO tbl_country_identification_code (code, nombre)
	VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newCountrySubentityCode
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newCountrySubentityCode`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newCountrySubentityCode`(
IN code VARCHAR(5),
IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_country_subentity_code (code, nombre)
        VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newEntidadAdjudicadora
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newEntidadAdjudicadora`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newEntidadAdjudicadora`(
	IN expedientes INT,
    IN ubicacion_organica VARCHAR(300),
    IN nombre VARCHAR(300),
    IN tipo_administracion INT,
    IN sitio_web VARCHAR(256),
    IN calle VARCHAR(220),
    IN codigo_postal VARCHAR(32),
    IN poblacion VARCHAR(90),
    IN pais VARCHAR(3),
    IN nombre_contacto VARCHAR(300),
    IN telefono VARCHAR(55),
    IN fax VARCHAR(55),
    IN correo_electronico VARCHAR(500),
    IN NIF VARCHAR(200),
    OUT entidad_adjudicadora INT)
BEGIN
		INSERT INTO tbl_entidad_adjudicadora (expedientes, ubicacion_organica, nombre, tipo_administracion, sitio_web, calle, codigo_postal, poblacion, pais, nombre_contacto, telefono, fax, correo_electronico, NIF)
		VALUES (expedientes, ubicacion_organica, nombre, tipo_administracion, sitio_web, calle, codigo_postal, poblacion, pais, nombre_contacto, telefono, fax, correo_electronico, NIF);
    
		SET entidad_adjudicadora = last_insert_id();
   
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newEntidadAdjudicadora_ID
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newEntidadAdjudicadora_ID`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newEntidadAdjudicadora_ID`(
	IN entidad_adjudicadora INT,
    IN id INT)
BEGIN
        INSERT INTO tbl_entidad_adjudicadora_id (entidad_adjudicadora, id) VALUES (entidad_adjudicadora, id);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newExpediente
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newExpediente`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newExpediente`(
	IN expedientes INT, 
	IN title VARCHAR(2000),
    IN link VARCHAR(2500),
    IN objeto_contrato VARCHAR(2000),
    IN valor_estimado DECIMAL(12,2),
    IN presupuesto_sin_impuestos DECIMAL(12,2),
    IN presupuesto_con_impuestos DECIMAL(12,2),
    IN start_date DATE, 
    IN end_date DATE,
    IN duracion DECIMAL(17,0),
    IN unitcode VARCHAR(45),
    IN typecode INT, 
    IN subtypecode INT)
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_expedientes (expedientes, title, link, objeto_contrato, valor_estimado, presupuesto_sin_impuestos,
				presupuesto_con_impuestos, start_date, end_date, duracion, unitcode, typecode, subtypecode)
		VALUES (expedientes, title, link, objeto_contrato, valor_estimado, presupuesto_sin_impuestos,
				presupuesto_con_impuestos, start_date, end_date, duracion, unitcode, typecode, subtypecode);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newExpediente_CPV
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newExpediente_CPV`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newExpediente_CPV`(
	IN code INT,
    IN expedientes INT)
BEGIN
	START TRANSACTION;
    
    INSERT INTO tbl_expediente_cpv (code, expedientes)
    VALUES (code, expedientes);
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newExpediente_Ids
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newExpediente_Ids`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newExpediente_Ids`(
	IN ids INT,
    IN expediente INT,
    IN summary VARCHAR(400),
    IN updated TIMESTAMP,
    IN estado VARCHAR(45))
BEGIN
		INSERT INTO tbl_ids_expedientes (ids, expediente, summary, updated, estado)
        VALUES (ids, expediente, summary, updated, estado);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newId
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newId`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newId`(
	IN entidad_adjudicadora INT,
    IN tipo_id VARCHAR(20),
    IN valor VARCHAR(45))
BEGIN
    
		INSERT INTO tbl_id (tipo_id, valor) VALUES (tipo_id, valor);
        CALL newEntidadAdjudicadora_ID ( entidad_adjudicadora, last_insert_id());
    

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newIds
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newIds`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newIds`(
	IN modos_id INT,
    OUT ids INT)
BEGIN 
	START TRANSACTION;
	INSERT INTO tbl_ids (modosid)
    VALUES (modos_id);
    
    SET ids = last_insert_id();
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newLanguage
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newLanguage`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newLanguage`(
	IN code VARCHAR(10),
    IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_language (code, nombre)
        VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newLugarDeEjecucion
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newLugarDeEjecucion`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newLugarDeEjecucion`(
	IN expedientes INT,
    IN subentidad_nacional VARCHAR(3),
    IN subentidad_territorial VARCHAR(5),
    IN pais VARCHAR(100),
    IN calle VARCHAR(220),
    IN codigo_postal VARCHAR(32),
    IN poblacion VARCHAR(90))
BEGIN
		INSERT INTO tbl_lugar_de_ejecucion (expedientes, subentidad_nacional, subentidad_territorial, pais, calle, codigo_postal, poblacion)
        VALUES (expedientes, subentidad_nacional, subentidad_territorial, pais, calle, codigo_postal, poblacion);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newModosId
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newModosId`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newModosId`(
	IN modosId INT,
    IN description VARCHAR(45))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_modosid (modosid, description)
        VALUES (modosId, description);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newPlazoDeObtencion
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newPlazoDeObtencion`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newPlazoDeObtencion`(
	IN expedientes INT,
    IN tipo_plazo INT,
    IN fecha DATE, 
    IN hora TIME,
    IN observaciones VARCHAR(550))
BEGIN
	INSERT INTO tbl_plazo_de_obtencion (fecha, hora, observaciones, expedientes, tipo_plazo) VALUES (fecha, hora, observaciones, expedientes, tipo_plazo);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newPliego
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newPliego`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newPliego`(
	IN id VARCHAR(200),
    IN uri VARCHAR(2500),
    IN document_hash VARCHAR(2500),
    IN file_name VARCHAR(2500),
    IN expedientes INT,
    IN tipo_pliego INT)
BEGIN
	START TRANSACTION;
    
		INSERT INTO tbl_pliegos (id, uri, document_hash, file_name, expedientes, tipo_pliego)
        VALUES (id, uri, document_hash, file_name, expedientes, tipo_pliego);
    
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newProcedureCode
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newProcedureCode`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newProcedureCode`(
	IN code INT,
    IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_procedure_code (code, nombre)
        VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newProcesoDeLicitacion
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newProcesoDeLicitacion`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newProcesoDeLicitacion`(
	IN expedientes INT,
    IN procedure_code INT,
    IN contracting_system_type_code INT,
    IN urgency_code INT,
    IN submission_method_code INT,
    IN procurement_legislation VARCHAR(15),
    IN subasta_electronica TINYINT,
    OUT proceso_de_licitacion INT)
BEGIN
		INSERT INTO tbl_proceso_de_licitacion (expedientes, tipo_procedimiento, sistema_contratacion, tramitacion, presentacion_oferta, regulacion, subasta_electronica)
        VALUES (expedientes, procedure_code, contracting_system_type_code, urgency_code, submission_method_code, procurement_legislation, subasta_electronica);
    
		SET proceso_de_licitacion = last_insert_id();
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newProcesoDeLicitacion_Idioma
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newProcesoDeLicitacion_Idioma`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newProcesoDeLicitacion_Idioma`(
	IN proceso_de_licitacion INT,
    IN idioma VARCHAR(10))
BEGIN
		INSERT INTO tbl_proceso_licitacion_idiomas (proceso_de_licitacion, idioma)
        VALUES (proceso_de_licitacion, idioma);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newProcurementLegislation
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newProcurementLegislation`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newProcurementLegislation`(
	IN code VARCHAR(15),
    IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_procurement_legislation (code, nombre)
        VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newSubmissionMethodCode
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newSubmissionMethodCode`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newSubmissionMethodCode`(
	IN code INT,
    IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_submission_method_code (code, nombre)
        VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newSubtypeCode
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newSubtypeCode`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newSubtypeCode`(
	IN code INT, 
    IN nombre VARCHAR(300),
    IN type_code INT)
BEGIN 
	INSERT INTO tbl_subtype_code (code, nombre, type_code)
    VALUES (code, nombre, type_code);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newTipoPlazo
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newTipoPlazo`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newTipoPlazo`(
	IN tipo_plazo INT,
    IN descripcion VARCHAR(45))
BEGIN
	START transaction;
    INSERT INTO tbl_tipo_plazo (tipo_plazo, descripcion) VALUES (tipo_plazo, descripcion);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newTipoPliego
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newTipoPliego`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newTipoPliego`(
	IN id INT,
    IN tipo VARCHAR(45))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_tipo_pliego (id, tipo)
        VALUES (id, tipo);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newTypeCode
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newTypeCode`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newTypeCode`(
	IN code INT,
    IN nombre VARCHAR(200))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_type_code (code, nombre)
        VALUES (code, nombre);
    COMMIT; 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure newUrgencyCode
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`newUrgencyCode`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `newUrgencyCode`(
	IN code INT,
    IN nombre VARCHAR(100))
BEGIN
	START TRANSACTION;
		INSERT INTO tbl_urgency_code (code, nombre)
        VALUES (code, nombre);
    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure searchExpediente
-- -----------------------------------------------------

USE `licitacion`;
DROP procedure IF EXISTS `licitacion`.`searchExpediente`;

DELIMITER $$
USE `licitacion`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `searchExpediente`(
	IN id INT, 
    OUT existe BOOLEAN)
BEGIN
	START TRANSACTION;
    SET existe = 
		CASE WHEN (SELECT COUNT(*) FROM tbl_expedientes WHERE expedientes = id) = 1 THEN 1
        ELSE 0
        END;
    COMMIT;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
